### PR TITLE
Add support for creating users and pages

### PR DESCRIPTION
**Pull request by joeyAghion**
I found these methods useful. They add support for creating pages (one of the simplest models) and users (one of the most quickly necessary models).

Until this point, the client didn't support creating data so didn't have relevant conventions in place. I guessed at a reasonable naming pattern but am not attached either way.

### CODE REVIEW

**Comment by joeyAghion** [comment]
@dblock I just added basic support for creating and updating artworks. I'm curious to get your thoughts. Feel free to point me to alternative client examples if you have a preferred pattern in mind.

**Comment by dblock** [comment]
This looks good. 

Travis is failing on Rubocop, which needs an upgrade. I'll take care of it.

**Comment by dblock** [comment]
Can you please update CHANGELOG and maybe README with an example for creating something? Bump Rubocop to the latest and build should be ok.

**Comment by joeyAghion** [comment]
Updated and built successfully.

**Comment by dblock** [comment]
Merged, gracias.

**Pull request merged**
