### PR TITLE
@ilyakava Fix api url of inquiry request.

### PR DESCRIPTION
**Pull request by starsirius**
Hey yo! Looks like recent sigma build failures were due to incorrect API endpoint used in the artsy client. Not sure why it succeeded before. Let me know if this makes sense to you, and I will rebuild sigma again after it's merged. Thanks!

Here is the error: http://joe.artsy.net:9000/job/sigma-integration/85/console

### CODE REVIEW

**Comment by dblock** [comment]
Build failed on Rubocop ...

**Comment by starsirius** [comment]
Weird. Only changed URL strings. Let me take a look. Thanks!!

**Comment by dblock** [comment]
It's possible that we somehow got a newer version of Rubocop here...

**Comment by starsirius** [comment]
Got it. Will fix that. Thanks!

**Comment by starsirius** [comment]
@dblock Done! Sorry that I forgot to follow up.

**Comment by dblock** [comment]
merged

**Comment by ilyakava** [comment]
@starsirius sorry for not seeing this, wasn't subscribed until now

I am stumped why the sigma specs ever passed using this api route... unfort looks like they still fail with the same errors as before :(

**Comment by starsirius** [comment]
@dblock thanks!
@ilyakava Hey no worries. Debugging sigma took a lot of time. :(  Will come back later. I guess we have to be creative somehow. : P

**Pull request merged**
