### PR TITLE
@starsirius: invoice management

### PR DESCRIPTION
**Pull request by joeyAghion**
I also tried to alphabetize the `require`s and `include`s, as they were getting unwieldy. Sorry about the big diff.

### CODE REVIEW

**Comment by starsirius** [comment]
Looks like rubocop errors.

**Comment by dylanfareed** [comment]
Thats quite possibly the most ticky-tack of all rubocop offenses - https://travis-ci.org/artsy/artsy-ruby-client/jobs/22153701#L66

image

**Comment by joeyAghion** [comment]
Rubocop conquered! The `Gemfile.lock` is `.gitignore`d, so Travis was running rubocop v0.20 and silly old me was running v0.18.

**Comment by starsirius** [comment]
Nice! Merging. Maybe we can include the Gemfile.lock.

**Comment by dblock** [comment]
Lock the Rubocop version in Gemfile (but don't commit Gemfile.lock).

**Pull request merged**
